version: "3"
services:
  enigma:
    image: "dessolo/enigma"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:rc-alpine"
